### ISSUE TITLE
Docker image UID problem on some Linux hosts

### ISSUE THREAD

**Issue by mwiewior** [ZSI-Bio/bdg-sequila#129]
https://zsibio.ii.pw.edu.pl/nexus/repository/maven-releases/ added as a remote repository with the name: repo-1
https://zsibio.ii.pw.edu.pl/nexus/repository/maven-snapshots/ added as a remote repository with the name: repo-2
Ivy Default Cache set to: /home/tempuser/.ivy2/cache
The jars for the packages stored in: /home/tempuser/.ivy2/jars
:: loading settings :: url = jar:file:/usr/local/spark-2.2.2-bin-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
org.biodatageeks#bdg-sequila_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
    confs: [default]
Exception in thread "main" java.io.FileNotFoundException: /home/tempuser/.ivy2/cache/resolved-org.apache.spark-spark-submit-parent-1.0.xml (No such file or directory)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
    at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorWriter.write(XmlModuleDescriptorWriter.java:70)
    at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorWriter.write(XmlModuleDescriptorWriter.java:62)
    at org.apache.ivy.core.module.descriptor.DefaultModuleDescriptor.toIvyFile(DefaultModuleDescriptor.java:563)
    at org.apache.ivy.core.cache.DefaultResolutionCacheManager.saveResolvedModuleDescriptor(DefaultResolutionCacheManager.java:176)
    at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:245)
    at org.apache.ivy.Ivy.resolve(Ivy.java:523)
    at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1195)
    at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:304)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:153)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

I have tested docker and SeQuiLa on Ubuntu 14.04 LTS and 18.04 LTS and have received the same error message. Do you know or have any idea what the problem could be?

______________________________________

**Comment by mwiewior** [comment]
resolved by #130
